version: '3'
services:
  coc-dice:
    build: .
    container_name: 'coc-dice'
    tty: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ".:/projects"
    working_dir: /projects
    ports:
      - 8501:8501
